import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-full w-full min-h-screen bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}
