import createSupabaseServerClient from "@/lib/supabase/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/styles.css";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SupabaseProvider from "./providers/supabase-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createSupabaseServerClient();


  // const { data, error } = await supabase?.auth?.getUser();
  // console.log({ data, error })
  return (
    <html lang="en" suppressHydrationWarning>
      <SupabaseProvider>
        <body className={`${inter.className} bg-black text-white h-full w-full min-h-screen`}>
          {children}
          <Toaster />
        </body>
      </SupabaseProvider>
    </html>
  );
}
